# Generated by Django 4.0.6 on 2022-08-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_favorited_unique_user_favorite_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_user_shopping_cart',
        ),
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='is_in_shopping_cart',
            new_name='shopping_cart',
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'shopping_cart'), name='unique_user_shopping_cart'),
        ),
    ]
