name: Django-app workflow
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        cd backend/
    - name: Test with flake8
      run: |
        python -m flake8
